// Vortex catalog loader — page code loads ONLY what it needs.
//
// Primary source: data/cosmetics/*.json (generated by scripts/sync-catalog.mjs).
// Fallback: legacy global COSMETICS_STORE (cosmetics-store.js) for file:// previews.
const cache = new Map();

function legacyItems() {
  try {
    if (typeof COSMETICS_STORE !== 'undefined' && COSMETICS_STORE && Array.isArray(COSMETICS_STORE.items)) {
      return COSMETICS_STORE.items;
    }
  } catch (e) {}
  return null;
}

export async function loadIndex() {
  if (cache.has('$index')) return cache.get('$index');
  try {
    const r = await fetch('data/cosmetics.json', { cache: 'force-cache' });
    if (!r.ok) throw new Error('http ' + r.status);
    const d = await r.json();
    cache.set('$index', d);
    return d;
  } catch (e) {
    const items = legacyItems() || [];
    const counts = {};
    for (const it of items) counts[it.cat] = (counts[it.cat] || 0) + 1;
    const d = { total: items.length, counts, categories: Object.keys(counts).sort(), legacy: true };
    cache.set('$index', d);
    return d;
  }
}

export async function loadCategory(cat) {
  if (cache.has(cat)) return cache.get(cat);
  try {
    const r = await fetch('data/cosmetics/' + encodeURIComponent(cat) + '.json', { cache: 'force-cache' });
    if (!r.ok) throw new Error('http ' + r.status);
    const d = await r.json();
    const items = Array.isArray(d.items) ? d.items : [];
    cache.set(cat, items);
    return items;
  } catch (e) {
    const items = (legacyItems() || []).filter(it => it.cat === cat);
    cache.set(cat, items);
    return items;
  }
}

export async function ensureLegacyShim() {
  if (legacyItems()) return true;
  try {
    await new Promise((resolve, reject) => {
      const s = document.createElement('script');
      s.src = 'cosmetics-store.js';
      s.onload = resolve;
      s.onerror = reject;
      document.head.appendChild(s);
    });
    return !!legacyItems();
  } catch (e) {
    return false;
  }
}

// Full item list from the generated shim (file:// preview path).
// The old store.js bundle is gone — this is the only fallback.
export async function loadAllLegacy() {
  await ensureLegacyShim();
  return legacyItems() || [];
}
