// Vortex catalog sync — LINK ACCOUNT COLLECTION (complete reset).
//
// Single source of truth: data/cosmetics/<capes|hats|pets>.json (one item
// each, all in the link-account collection) + the collection record at
// cosmetics/collections/link-account/collection.json.
// There is EXACTLY ONE collection with EXACTLY 3 items; this script fails
// the build on anything else.
//
// Outputs (all generated, deterministic, no base64/assets inside JS):
//   data/cosmetics.json              (index: categories, counts, total)
//   data/cosmetics/<cat>.json        (re-normalized, img/texture verified)
//   cosmetics-store.js               (legacy global shim: var COSMETICS_STORE)
//
// Every item's image ALWAYS comes from its own `img` field
// (cosmetics/<cat>/<file>_preview.webp); the client texture ALWAYS comes
// from its own `texture` field. Both must exist on disk, case-sensitively.
// The store never constructs paths from ids.
//
// Usage: node scripts/sync-catalog.mjs
import { readFileSync, writeFileSync, existsSync, readdirSync, statSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const GEN = '// GENERATED by scripts/sync-catalog.mjs — do not edit by hand. Edit data/cosmetics/<cat>.json instead.\n';

const RARITIES = new Set(['Common', 'Rare', 'Epic', 'Legendary', 'Mythic']);
const CATS = ['capes', 'hats', 'pets'];

function fail(msg) { console.error('sync-catalog: ERROR: ' + msg); process.exit(1); }

// Case-sensitive existence (Windows FS is case-insensitive; prod is not).
function existsCaseSensitive(rel) {
  const parts = String(rel).split('/');
  let cur = ROOT;
  for (const p of parts) {
    if (!p || p === '.') continue;
    if (p === '..') return false;
    let entries;
    try { entries = readdirSync(cur); } catch { return false; }
    if (!entries.includes(p)) return false;
    cur = join(cur, p);
  }
  return true;
}

const byCat = {};
let all = [];
for (const cat of CATS) {
  const file = join(ROOT, 'data', 'cosmetics', cat + '.json');
  let src;
  try {
    src = JSON.parse(readFileSync(file, 'utf8'));
  } catch (e) {
    fail('cannot read ' + file + ': ' + e.message);
  }
  const items = Array.isArray(src.items) ? src.items : [];
  if (!items.length) fail(cat + ' source has no items');
  byCat[cat] = items;
  all = all.concat(items);
}

// No other active category payload may exist.
for (const f of readdirSync(join(ROOT, 'data', 'cosmetics'))) {
  if (f.endsWith('.json') && !CATS.includes(f.replace(/\.json$/, ''))) {
    fail('unexpected category payload data/cosmetics/' + f);
  }
}

const seen = new Set();
for (const it of all) {
  if (!it.id || typeof it.id !== 'string') fail('item without id');
  if (seen.has(it.id)) fail('duplicate id: ' + it.id);
  seen.add(it.id);
  if (!CATS.includes(it.cat)) fail(it.id + ': bad cat ' + it.cat);
  if (!it.name) fail(it.id + ': missing name');
  if (!RARITIES.has(it.rarity)) fail(it.id + ': bad rarity ' + it.rarity);
  if (!Number.isFinite(Number(it.price)) || Number(it.price) <= 0) {
    fail(it.id + ': bad price');
  }
  if (!it.img || typeof it.img !== 'string') fail(it.id + ': missing img field');
  if (!it.img.endsWith('.webp')) fail(it.id + ': img must be .webp (got ' + it.img + ')');
  if (!it.img.startsWith('cosmetics/' + it.cat + '/')) {
    fail(it.id + ': img must live in cosmetics/' + it.cat + '/ (got ' + it.img + ')');
  }
  if (!existsCaseSensitive(it.img)) fail(it.id + ': MISSING asset ' + it.img);
  if (!Array.isArray(it.tags) || !it.tags.length) fail(it.id + ': missing tags');
  if (!it.theme || typeof it.theme !== 'string') fail(it.id + ': missing theme');
  if (!it.desc) fail(it.id + ': missing desc');
  if (typeof it.animated !== 'boolean') fail(it.id + ': animated must be boolean');
  if (typeof it.vortexPlus !== 'boolean') fail(it.id + ': vortexPlus must be boolean');
  // Honest status vocabulary: "functional" ONLY when the Vortex client
  // actually supports the item, otherwise "preview-only". Never claim
  // functional by default.
  if (it.status !== 'functional' && it.status !== 'preview-only') {
    fail(it.id + ': status must be functional|preview-only (got ' + it.status + ')');
  }
  if (!it.texture || typeof it.texture !== 'string') fail(it.id + ': missing texture field');
  if (!it.texture.endsWith('.png')) fail(it.id + ': texture must be .png (got ' + it.texture + ')');
  if (!it.texture.startsWith('cosmetics/' + it.cat + '/')) {
    fail(it.id + ': texture must live in cosmetics/' + it.cat + '/ (got ' + it.texture + ')');
  }
  if (!existsCaseSensitive(it.texture)) fail(it.id + ': MISSING texture ' + it.texture);
  if (it.model && !existsCaseSensitive(it.model)) fail(it.id + ': MISSING model ' + it.model);
  if (!it.collection || typeof it.collection !== 'string') fail(it.id + ': missing collection');
}

// EXACTLY ONE collection with EXACTLY the catalog items.
const colRoot = join(ROOT, 'cosmetics', 'collections');
let colDirs = [];
try {
  colDirs = readdirSync(colRoot).filter((d) => {
    try { return statSync(join(colRoot, d)).isDirectory(); } catch { return false; }
  });
} catch (e) {
  fail('missing cosmetics/collections/');
}
if (colDirs.length !== 1) fail('must be exactly 1 collection, found: ' + JSON.stringify(colDirs));
const colFile = join(colRoot, colDirs[0], 'collection.json');
let col;
try {
  col = JSON.parse(readFileSync(colFile, 'utf8'));
} catch (e) {
  fail('cannot read ' + colFile + ': ' + e.message);
}
if (!col.id || !col.name || !Array.isArray(col.items)) fail('bad collection.json shape');
if (col.items.length !== all.length) {
  fail('collection must list exactly the catalog items (' + all.length + ')');
}
for (const id of col.items) {
  if (!seen.has(id)) fail('collection lists unknown item ' + id);
}
for (const it of all) {
  if (it.collection !== col.id) fail(it.id + ': collection must be ' + col.id);
}
const colPreview = join(colRoot, colDirs[0], 'preview.webp');
if (!existsSync(colPreview)) fail('missing collection preview ' + colPreview);

const updatedAt = new Date().toISOString();
const counts = {};
for (const cat of CATS) {
  const items = byCat[cat].map((it) => ({
    id: it.id,
    name: it.name,
    cat,
    type: it.type || cat.slice(0, -1).toUpperCase(),
    slot: it.slot || cat.slice(0, -1).toUpperCase(),
    rarity: it.rarity,
    price: Number(it.price),
    desc: it.desc,
    tags: it.tags,
    theme: it.theme,
    img: it.img,
    model: it.model || null,
    texture: it.texture || null,
    // animated is true ONLY when the real client implements the motion.
    animated: !!it.animated,
    effects: Array.isArray(it.effects) ? it.effects : [],
    status: it.status || 'preview-only',
    vortexPlus: !!it.vortexPlus,
    featured: !!it.featured,
    isNew: !!it.isNew,
    features: Array.isArray(it.features) ? it.features : [],
    collection: it.collection,
  }));
  counts[cat] = items.length;
  writeFileSync(join(ROOT, 'data', 'cosmetics', cat + '.json'),
    JSON.stringify({ category: cat, count: items.length, updatedAt, items }, null, 2) + '\n');
}

writeFileSync(join(ROOT, 'data', 'cosmetics.json'),
  JSON.stringify({
    updatedAt,
    total: all.length,
    counts,
    categories: CATS.slice().sort(),
  }, null, 2) + '\n');

// shim for file:// fallback (same shape, single img per item from item.img)
const shimItems = [];
for (const cat of CATS) {
  const d = JSON.parse(readFileSync(join(ROOT, 'data', 'cosmetics', cat + '.json'), 'utf8'));
  for (const it of d.items) {
    shimItems.push({
      id: it.id, name: it.name, cat: it.cat, type: it.type,
      rarity: it.rarity, price: it.price, desc: it.desc, img: it.img,
      tags: it.tags || [], theme: it.theme || null, outfit: null,
      animated: !!it.animated, effects: it.effects || [],
      status: it.status || 'preview-only', vortexPlus: !!it.vortexPlus,
      featured: !!it.featured, isNew: !!it.isNew,
      features: it.features || [], collection: it.collection || null,
      texture: it.texture || null, model: it.model || null,
    });
  }
}
writeFileSync(join(ROOT, 'cosmetics-store.js'),
  GEN + 'var COSMETICS_STORE = ' + JSON.stringify({ items: shimItems }) + ';\n');

console.log(`sync-catalog: ok — ${all.length} items, collection=${col.id} [${col.items.join(', ')}]`);
