// Vortex catalog sync — CAPES-ONLY store (complete store reset, Oct 2026).
//
// Single source of truth: data/cosmetics/capes.json (hand-curated starter
// collection). Previous multi-category sources (VortexBot catalog +
// vortex-menu-mod index) are ARCHIVED under data/archive/ along with the
// old category payloads — the files stay on disk for future categories
// (wings, pets, auras, suits, headwear, ...) but NOTHING outside capes
// may enter the active catalog until a category is genuinely reintroduced.
//
// Outputs (all generated, deterministic, no base64/assets inside JS):
//   data/cosmetics.json              (index: categories == ["capes"])
//   data/cosmetics/capes.json        (re-normalized from source, img verified)
//   cosmetics-store.js               (legacy global shim: var COSMETICS_STORE)
//
// Every item's image ALWAYS comes from its own `img` field
// (cosmetics/capes/<file>.webp) and must exist on disk, case-sensitively,
// as valid WebP. The store never constructs paths from ids.
//
// Usage: node scripts/sync-catalog.mjs
import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, 'data', 'cosmetics', 'capes.json');
const GEN = '// GENERATED by scripts/sync-catalog.mjs — do not edit by hand. Edit data/cosmetics/capes.json instead.\n';

const RARITIES = new Set(['Common', 'Rare', 'Epic', 'Legendary', 'Mythic']);

function fail(msg) { console.error('sync-catalog: ERROR: ' + msg); process.exit(1); }
function warn(msg) { console.error('sync-catalog: WARN: ' + msg); }

// Case-sensitive existence (Windows FS is case-insensitive; prod is not).
function existsCaseSensitive(rel) {
  const parts = String(rel).split('/');
  let cur = ROOT;
  for (const p of parts) {
    if (!p || p === '.') continue;
    if (p === '..') return false;
    let entries;
    try { entries = readdirSync(cur); } catch { return false; }
    if (!entries.includes(p)) return false;
    cur = join(cur, p);
  }
  return true;
}

let src;
try {
  src = JSON.parse(readFileSync(SRC, 'utf8'));
} catch (e) {
  fail('cannot read capes source ' + SRC + ': ' + e.message);
}
const items = Array.isArray(src.items) ? src.items : [];
if (!items.length) fail('capes source has no items');

// CAPES ONLY gate: no other active category payload may exist.
for (const f of readdirSync(join(ROOT, 'data', 'cosmetics'))) {
  if (f.endsWith('.json') && f !== 'capes.json') {
    fail('active catalog must be capes-only, found data/cosmetics/' + f +
      ' (move it to data/archive/)');
  }
}

const seen = new Set();
for (const it of items) {
  if (!it.id || typeof it.id !== 'string') fail('item without id');
  if (seen.has(it.id)) fail('duplicate id: ' + it.id);
  seen.add(it.id);
  if (it.cat !== 'capes') fail(it.id + ': cat must be "capes" (got ' + it.cat + ')');
  if (!it.name) fail(it.id + ': missing name');
  if (!RARITIES.has(it.rarity)) fail(it.id + ': bad rarity ' + it.rarity);
  if (!Number.isFinite(Number(it.price)) || Number(it.price) <= 0) {
    fail(it.id + ': bad price');
  }
  if (!it.img || typeof it.img !== 'string') fail(it.id + ': missing img field');
  if (!it.img.endsWith('.webp')) fail(it.id + ': img must be .webp (got ' + it.img + ')');
  if (!it.img.startsWith('cosmetics/capes/')) {
    fail(it.id + ': img must live in cosmetics/capes/ (got ' + it.img + ')');
  }
  if (!existsCaseSensitive(it.img)) fail(it.id + ': MISSING asset ' + it.img);
  if (!Array.isArray(it.tags) || !it.tags.length) fail(it.id + ': missing tags');
  if (!it.theme || typeof it.theme !== 'string') fail(it.id + ': missing theme');
  if (!it.desc) fail(it.id + ': missing desc');
  if (typeof it.animated !== 'boolean') fail(it.id + ': animated must be boolean');
  if (typeof it.vortexPlus !== 'boolean') fail(it.id + ': vortexPlus must be boolean');
  // Honest status vocabulary: "functional" ONLY when the Vortex client
  // actually supports the cape, otherwise "preview-only". Never claim
  // functional by default.
  if (it.status !== 'functional' && it.status !== 'preview-only') {
    fail(it.id + ': status must be functional|preview-only (got ' + it.status + ')');
  }
  if (!it.texture || typeof it.texture !== 'string') fail(it.id + ': missing texture field');
  if (!it.texture.endsWith('.png')) fail(it.id + ': texture must be .png (got ' + it.texture + ')');
  if (!it.texture.startsWith('cosmetics/capes/')) {
    fail(it.id + ': texture must live in cosmetics/capes/ (got ' + it.texture + ')');
  }
  if (!existsCaseSensitive(it.texture)) fail(it.id + ': MISSING texture ' + it.texture);
}

const updatedAt = new Date().toISOString();
const out = {
  category: 'capes',
  count: items.length,
  updatedAt,
  items: items.map((it) => ({
    id: it.id,
    name: it.name,
    cat: 'capes',
    type: it.type || 'CAPE',
    slot: it.slot || 'CAPE',
    rarity: it.rarity,
    price: Number(it.price),
    desc: it.desc,
    tags: it.tags,
    theme: it.theme,
    img: it.img,
    model: it.model || null,
    texture: it.texture || null,
    // animated is true ONLY when the real client implements the motion.
    animated: !!it.animated,
    effects: Array.isArray(it.effects) ? it.effects : [],
    status: it.status || 'preview-only',
    vortexPlus: !!it.vortexPlus,
    featured: !!it.featured,
    isNew: !!it.isNew,
    features: Array.isArray(it.features) ? it.features : [],
  })),
};
writeFileSync(SRC, JSON.stringify(out, null, 2) + '\n');

writeFileSync(join(ROOT, 'data', 'cosmetics.json'),
  JSON.stringify({
    updatedAt,
    total: out.items.length,
    counts: { capes: out.items.length },
    categories: ['capes'],
  }, null, 2) + '\n');

// shim for file:// fallback (same shape, single img per item from item.img)
const shimItems = out.items.map((it) => ({
  id: it.id, name: it.name, cat: it.cat, type: it.type,
  rarity: it.rarity, price: it.price, desc: it.desc, img: it.img,
  tags: it.tags || [], theme: it.theme || null, outfit: null,
  animated: !!it.animated, effects: it.effects || [],
  status: it.status || 'preview-only', vortexPlus: !!it.vortexPlus,
  featured: !!it.featured, isNew: !!it.isNew,
  features: it.features || [],
}));
writeFileSync(join(ROOT, 'cosmetics-store.js'),
  GEN + 'var COSMETICS_STORE = ' + JSON.stringify({ items: shimItems }) + ';\n');

if (!existsSync(join(ROOT, 'data', 'archive', 'cloaks.json'))) {
  warn('data/archive/ has no pre-reset snapshot (expected cloaks.json etc.)');
}
console.log(`sync-catalog: ok — ${out.items.length} capes, categories=["capes"]`);
